### ISSUE TITLE
Black Screen while attempting to render rods in hand

### ISSUE THREAD

**Issue by Jaidenjk** [TheIllusiveC4/MagicalPsi#1]
Simply put, everytime I attempt to hold a rod, the screen just stops rendering anything. The game still runs, as I am able to navigate the pause menu and main menu via sound, but there are no longer any visuals. Image pending.

**Comment by TheIllusiveC4** [comment]
Sorry for the late response, I apparently did not set up notifications for this repo correctly.

Can you verify that this only occurs with Magical Psi and not Psi by itself? In addition, have you tried testing if this happens with ONLY Magical Psi, Psi, and Patchouli installed? Also, are there any errors logged in the console when this happens?

**Comment by Jaidenjk** [comment]
apologies for the later response, it seems to be an issue with Psi's shader system, disabling it seems to have fixed the issue. In console, no errors were ever logged, so i think its on Psi's end. Side note, the rendering on the armor is also bugged, as the helmet renders as a green color, and the other pieces don't render at all.

**Comment by TheIllusiveC4** [comment]
Does the armor rendering bug still happen with the shader system off? And does it happen if you have only Magical Psi + Psi installed?

**Comment by Jaidenjk** [comment]
To the first question, it does. Second question i have to test, ill get back to you on that

**Comment by TheIllusiveC4** [comment]
As an addendum, make sure to test with the latest Psi version as a new build was released yesterday that fixed a possibly related armor bug.

**Comment by Jaidenjk** [comment]
alright, so the armor render issue was fixed in version r1.2-84, but not the green helmet

https://cdn.discordapp.com/attachments/733626092136431659/756996386104410192/unknown.png
